Areas/Admin/Controllers/CategogiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using Bonsal_Gardent.Areas.Admin.Data;
using PagedList;

namespace Bonsal_Gardent.Areas.Admin.Controllers
{
    public class CategogiesController : Controller
    {
        private Bonsal_GardentEntities db = new Bonsal_GardentEntities();

        // GET: Admin/Categogies
        public ActionResult Index(string search, int? index)
        {
            var data = db.Categogies;
            if (search.IsEmpty())
            {
                return View(data.ToList().ToPagedList(index ?? 1, 3));
            }
            if (search.IsInt())
            {
                return View(data.ToList().Where(x => x.ID.Equals(Convert.ToInt32(search))).ToPagedList(index ?? 1, 3));
            }
            return View(data.ToList().Where(x => x.Name.StartsWith(search)).ToPagedList(index ?? 1, 3));
        }
        // GET: Admin/Categogies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categogy categogy = db.Categogies.Find(id);
            if (categogy == null)
            {
                return HttpNotFound();
            }
            return View(categogy);
        }

        // GET: Admin/Categogies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Categogies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Categogy categogy)
        {
            if (ModelState.IsValid)
            {
                db.Categogies.Add(categogy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categogy);
        }

        // GET: Admin/Categogies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categogy categogy = db.Categogies.Find(id);
            if (categogy == null)
            {
                return HttpNotFound();
            }
            return View(categogy);
        }

        // POST: Admin/Categogies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Categogy categogy)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categogy).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categogy);
        }

        // GET: Admin/Categogies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categogy categogy = db.Categogies.Find(id);
            if (categogy == null)
            {
                return HttpNotFound();
            }
            return View(categogy);
        }

        // POST: Admin/Categogies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categogy categogy = db.Categogies.Find(id);
            db.Categogies.Remove(categogy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/Categogies/Create.cshtml
@model Bonsal_Gardent.Areas.Admin.Data.Categogy

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create Categogy</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-dark" })
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/Categogies/Delete.cshtml
@model Bonsal_Gardent.Areas.Admin.Data.Categogy

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h3>Are you sure you want to delete this category ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
    <hr />
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index",null,new {@class="btn btn-dark"})
        </div>
    }
</div>

Areas/Admin/Views/Categogies/Details.cshtml
@model Bonsal_Gardent.Areas.Admin.Data.Categogy

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details Categogy</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<hr />
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID },new {@class="btn btn-primary"}) |
    @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-dark" })
</p>

Areas/Admin/Views/Categogies/Edit.cshtml
@model Bonsal_Gardent.Areas.Admin.Data.Categogy

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit Categogy</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index",null,new {@class="btn btn-dark"})
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/Categogies/Index.cshtml
@model PagedList.IPagedList<Bonsal_Gardent.Areas.Admin.Data.Categogy>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Category List</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success" })
</p>
@using PagedList.Mvc;
@using PagedList;

<p>
    @using (Html.BeginForm("Index", "Categogies", FormMethod.Get))
    {
        <div class="input-group">
            <input name="search" type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
            <button type="submit" class="btn btn-dark">search</button>
        </div>
    }
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>
<p class="fw-bold">@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</p>
<br />
<div id="PageList">
    @Html.PagedListPager(Model, index => Url.Action("Index", "Categogies", new { index, search = Request.QueryString["search"] }))
</div>