Areas/Admin/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bonsal_Gardent.Areas.Admin.Data;
using PagedList.Mvc;
using PagedList;
using System.Web.WebPages;

namespace Bonsal_Gardent.Areas.Admin.Controllers
{
    public class PicturesController : Controller
    {
        private Bonsal_GardentEntities db = new Bonsal_GardentEntities();

        // GET: Admin/Pictures
        public ActionResult Index(string search,int? index)
        {
            var pictures = db.Pictures.Include(p => p.Product);
            if (search.IsEmpty())
            {
                return View(pictures.ToList().ToPagedList(index ?? 1, 3));
            }
            if(search.IsInt())
            {
                return View(pictures.ToList().Where(x=>x.ID.Equals(Convert.ToInt32(search))).ToPagedList(index ?? 1, 3));
            }
            return View(pictures.ToList().Where(x=>x.Product.Name.StartsWith(search)).ToPagedList(index ?? 1,3));
        }

        // GET: Admin/Pictures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // GET: Admin/Pictures/Create
        public ActionResult Create()
        {
            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name");
            return View();
        }

        // POST: Admin/Pictures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProductID,Path,TypeID")] Picture picture, HttpPostedFileBase[] PostedFile)
        {
            if (ModelState.IsValid)
            {
                string path = "";
                if (PostedFile[0] != null)
                {
                    foreach (HttpPostedFileBase file in PostedFile)
                    {
                        string InputFileName = picture.ID+"-"+picture.ProductID+"-"+Path.GetFileName(file.FileName);
                        var ServerSavePath = Path.Combine(Server.MapPath("~/Images/UploadedFiles/") + InputFileName);
                        //Save file to server folder  
                        file.SaveAs(ServerSavePath);
                        path += InputFileName + ",";
                    }
                }
                else
                {
                    path = "Default.jpg,"; 
                }
                path = path.Remove(path.Length - 1);
                picture.Path = path;
                db.Pictures.Add(picture);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name", picture.ProductID);
            return View(picture);
        }

        // GET: Admin/Pictures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name", picture.ProductID);
            return View(picture);
        }

        // POST: Admin/Pictures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProductID,Path,TypeID")] Picture picture, HttpPostedFileBase[] PostedFile)
        {
            if (ModelState.IsValid)
            {
                //Get old paths
                string paths = picture.Path;
                //Delete Old Image
                if (paths != null)
                {
                    string[] pathss = paths.Split(',');
                    foreach (var item in pathss)
                    {
                        string fullPath = Request.MapPath("~/Images/UploadedFiles/" + item);
                        if (System.IO.File.Exists(fullPath))
                        {
                            System.IO.File.Delete(fullPath);
                        }
                    }
                }
                //Modified
                string path = "";
                if (PostedFile[0] != null)
                {
                    foreach (HttpPostedFileBase file in PostedFile)
                    {
                        string InputFileName = picture.ID + "-" + picture.ProductID + "-" + Path.GetFileName(file.FileName);
                        var ServerSavePath = Path.Combine(Server.MapPath("~/Images/UploadedFiles/") + InputFileName);
                        //Save file to server folder  
                        file.SaveAs(ServerSavePath);
                        path += InputFileName + ",";
                    }
                }
                else
                {
                    path = "Default.jpg,";
                }
                path = path.Remove(path.Length - 1);
                picture.Path = path;
                //Modified Image
                db.Entry(picture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name", picture.ProductID);
            return View(picture);
        }

        // GET: Admin/Pictures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // POST: Admin/Pictures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Picture picture = db.Pictures.Find(id);
            db.Pictures.Remove(picture);
            string path = picture.Path;
            db.SaveChanges();
            if (path != "Default.jpg")
            {
                string[] paths = path.Split(',');
                foreach (var item in paths)
                {
                    string fullPath = Request.MapPath("~/Images/UploadedFiles/" + item);
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }
                }
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/Pictures/Create.cshtml
@model Bonsal_Gardent.Areas.Admin.Data.Picture

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create Picture</h2>


@using (Html.BeginForm("Create","Pictures",FormMethod.Post,new {enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ProductID, "ProductID", htmlAttributes: new { @class = "control-label col-md-2 TitleAdmin" })
        <div class="col-md-10">
            @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2 TitleAdmin" })
        <div class="col-md-10">
            <input class="form-control" type="file" name="PostedFile" multiple />
        </div>
    </div>
  
    @*<div class="form-group">
            @Html.LabelFor(model => model.TypeID, htmlAttributes: new { @class = "control-label col-md-2 TitleAdmin" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </div>
        </div>*@
    <hr />
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-success" />
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-dark" })
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/Pictures/Delete.cshtml
@model Bonsal_Gardent.Areas.Admin.Data.Picture

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h3>Are you sure you want to delete this picture?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index",null,new {@class="btn btn-dark"})
        </div>
    }
</div>

Areas/Admin/Views/Pictures/Details.cshtml
@model Bonsal_Gardent.Areas.Admin.Data.Picture

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Picture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Product.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Path)
        </dd>

        <dt>
            @{string[] Path = @Html.DisplayFor(model => model.Path).ToString().Split(',');}
            @foreach (var image in Path)
            {
                <img src="~/Images/UploadedFiles/@image" class="w-25 h-25 shadow-sm" />
            }
        </dt>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID },new {@class="btn btn-primary"}) 
    @Html.ActionLink("Back to List", "Index", null, new {@class="btn btn-dark"})
</p>

Areas/Admin/Views/Pictures/Edit.cshtml
@model Bonsal_Gardent.Areas.Admin.Data.Picture

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit Picture</h2>


@using (Html.BeginForm("Edit", "Pictures", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, "ProductID", htmlAttributes: new { @class = "control-label col-md-2 TitleAdmin" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2 TitleAdmin" })
            <div class="col-md-10">
                @{string[] Path = @Html.DisplayFor(model => model.Path).ToString().Split(',');}
                @foreach (var image in Path)
                {
                    <img src="~/Images/UploadedFiles/@image" class="shadow-sm img-sm" />
                }
            </div>
            <br />
            <div class="col-md-10">
                <input class="form-control" type="file" name="PostedFile" multiple required/>
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TypeID, htmlAttributes: new { @class = "control-label col-md-2 TitleAdmin" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <hr />
        <div class="form-group">
            <input type="submit" value="Replace" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-dark" })
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/Pictures/Index.cshtml
@model PagedList.IPagedList<Bonsal_Gardent.Areas.Admin.Data.Picture>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Picture of product list</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success" })
</p>
<p>
    @using (Html.BeginForm("Index", "Pictures", FormMethod.Get))
    {
        <div class="input-group">
            <input name="search" type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
            <button type="submit" class="btn btn-dark">search</button>
        </div>
    }
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Product.Name)
        </th>
        <th class="slide-container">
            @Html.DisplayNameFor(model => model.First().Path)
        </th>
        @*
        <th>
            @Html.DisplayNameFor(model => model.First().TypeID)
        </th>*@

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.Name)
            </td>
            <td>
                <div class="slide-container">
                    @{string[] Path = @Html.DisplayFor(modelItem => item.Path).ToString().Split(',');}
                    @foreach (var image in Path)
                    {
                        <img src="~/Images/UploadedFiles/@image" class="img-sm" />
                    }
                </div>
            </td>
            @*
        <td>
            @Html.DisplayFor(modelItem => item.TypeID)
        </td>*@
            <td style="width:10%;">
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-primary m-1 w-100" })
                @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-success m-1 w-100" })
                @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger m-1 w-100" })
            </td>
        </tr>
    }

</table>
<p class="fw-bold">@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</p>
<br />
<div id="PageList">
    @Html.PagedListPager(Model, index => Url.Action("Index", "Pictures", new { index, search = Request.QueryString["search"] }))
</div>